### ISSUE TITLE
Support a gambling system

### ISSUE THREAD

**Issue by billbindi** [kizyahaha/MSB_website_design#14]
Is there a "fair" way we can integrate in a gambling system for posts to try to win some extra boks?

**Comment by kizyahaha** [comment]
- Knowing the power or even the relative power of rants will have a detrimental effect on a gambling system.
- Will this encourage people to upvote only what they THINK will win?  For example, I hate cat pictures, but I'd place a bet on a cat picture and then upvote it because other people eat that shit up and it is likely to win.

**Comment by kizyahaha** [comment]
When would you actually get a payout?  Say I place a bet on a rant in the minutely level.  What if it doesn't win the minutely level until 37 minutes after I bet on it?  What if it then goes on to win the daily level?

**Comment by kizyahaha** [comment]
Closing.  No longer relevant to the site.
